name: linux-cmake.yml

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use HTTPS for submodules in CI
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libvulkan-dev libx11-dev libxrandr-dev libxi-dev libxcursor-dev libxinerama-dev

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target StarWarsCardGameTest -- -j 14

      - name: Run tests
        run: ./build/StarWarsCardGameTest > test_results.txt

