name: rpi-ubuntu-cmake.yml

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target StarWarsCardGameTest -- -j 14

      - name: Run tests
        run: ./build/StarWarsCardGameTest > test_results.txt